### ISSUE TITLE
Don't get .NET dll for certain MavenReference

### ISSUE THREAD

**Issue by martin-honnen** [ikvmnet/ikvm-maven#16]
When I write a Java project with Maven dependencies
```
   <dependencies>
        <dependency>
            <groupId>org.exist-db.thirdparty.xerces</groupId>
            <artifactId>xercesImpl</artifactId>
            <version>2.12.2</version>
            <classifier>xml-schema-1.1</classifier>
        </dependency>

        <!-- xpath2 and java-cup are needed at runtime
                for xercesImpl Schema 1.1 support -->
        <dependency>
            <groupId>org.exist-db.thirdparty.org.eclipse.wst.xml</groupId>
            <artifactId>xpath2</artifactId>
            <version>1.2.0</version>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>edu.princeton.cup</groupId>
            <artifactId>java-cup</artifactId>
            <version>10k</version>
            <scope>runtime</scope>
        </dependency>
    </dependencies>
```

then part of the used jars is e.g. `C:\Users\marti\.m2\repository\edu\princeton\cup\java-cup\10k\java-cup-10k.jar`.

However, with IKVM Maven, when I use e.g. 
```
<ItemGroup>
    <PackageReference Include="IKVM.Maven.Sdk" Version="1.0.1" />
	<MavenReference Include="org.exist-db.thirdparty.xerces:xercesImpl" Version="2.12.2" Classifier="xml-schema-1.1"/>
	<MavenReference Include="org.exist-db.thirdparty.org.eclipse.wst.xml:xpath2" Version="1.2.0" />
	<MavenReference Include="edu.princeton.cup:java-cup" Version="10k" />
  </ItemGroup>
```
and build, I don't seem to get any dll for `java-cup`, I only get e.g. `xercesImpl.dll`, `xml.apis.dll` and `xpath2.dll`.

Is that due to the odd `Version="10k"`? Any idea how to fix that, other than to not use MavenReference but include the jar file?

**Comment by NightOwl888** [comment]
I believe so. Although version numbers in Java are alphanumeric (i.e. 1.0-SNAPSHOT is a valid version), in .NET they are strictly numeric.

When passed through this [NormalizeAssemblyVersion](https://github.com/ikvm-revived/ikvm/blob/00f12ee840253b708ab9356341e0ff9ce3f9d5c3/src/IKVM.MSBuild.Tasks/IkvmReferenceItemPrepare.cs#L198-L213), we will end up with a null version number because the .NET `Version` class will fail to parse it. I don't know if that specifically applies to `IkvmReference`, but it is definitely a bug to assume `Version.TryParse` can normalize any Java version number.

**Comment by NightOwl888** [comment]
More examples of version numbers that won't pass the `Version.TryParse` validation.

- [0.0.95-b3](https://search.maven.org/artifact/com.greedygame.sdkx/commons/0.0.95-b3/aar)
- [1.4.0-rc.1](https://search.maven.org/artifact/com.ably.tracking/common/1.4.0-rc.1/aar)
- [1.1-alpha.16](https://search.maven.org/artifact/com.gitlab.taucher2003.t2003-utils/common/1.1-alpha.16/jar)
- [2.1.3-dev-220924](https://search.maven.org/artifact/io.devbench.uibuilder.components.util/common/2.1.3-dev-220924/jar)
- [1.0-RC6](https://search.maven.org/artifact/com.octo.captcha/jcaptcha-all/1.0-RC6/jar)
- [2.7-RELEASE](https://search.maven.org/artifact/io.afu/common/2.7-RELEASE/jar)
- [1.2.wso2v1](https://search.maven.org/artifact/org.wso2.orbit.re2j/re2j/1.2.wso2v1/bundle)
- [1.16.0-M1](https://search.maven.org/artifact/org.fomkin/korolev-ce2_3/1.16.0-M1/jar)
- [0.1.6-444a405](https://search.maven.org/artifact/zone.gryphon.do/digitalocean-java-bom/0.1.6-444a405/pom)
- [8.0.0-139](https://search.maven.org/artifact/org.restcomm.resources/services-DU/8.0.0-139/jar)
- [1.0.18-Helium-SR4](https://search.maven.org/artifact/org.opendaylight.defense4all/defenseflow.dp/1.0.18-Helium-SR4/jar)
- [1.0.0.RELEASE](https://search.maven.org/artifact/io.r2dbc/r2dbc-proxy/1.0.0.RELEASE/jar)

I can't seem to locate any official docs on what formats are supported in Java, but it is clear that there are few limitations. But it appears safe to assume the start of the string will always contain the numbers.

## Getting a Valid .NET Version Number

To get a valid .NET version number, it seems the best way would be to analyze the version string from the beginning and capture everything that matches `[0-9.]`. If the string then ends in a `.`, append a `0`. Then run it through `Version.TryParse` as we are currently doing.

## Handling Uniqueness (for cache)

Discarding characters from the version number increases the chances of there being collisions in the cache. This will be an issue for successive prereleases (1.0.0-RC1 vs 1.0.0-RC2).

The way to fix this would be to pass through the *actual* version number from Java to the cache so we can be sure it is in a unique folder. It would also be ideal to put the *actual* version number into the `AssemblyInformationalVersion` field so it is possible to examine a compiled DLL and determine what Java version (including prereleases) it corresponds to.

@wasabii - I attempted to look for the code that caches the compiled DLLs that you previously mentioned when dealing with `IkvmReference`, but couldn't find it. Nor could I find a cache in my /user folder. Was this cut from the project?

**Comment by wasabii** [comment]
https://github.com/ikvm-revived/ikvm/blob/eccfef126220d8dd339bdf27fa4b1de4bae949ed/src/IKVM.Util/Modules/ModuleVersion.cs

**Comment by wasabii** [comment]
~/.ikvm/cache

**Comment by wasabii** [comment]
This appears to be https://github.com/ikvm-revived/ikvm/issues/100, which is fixed in IKVM/develop (8.2.2).

As the problem exists in IkvmReference itself, and MavenReference automatically creates IkvmReferences, and does not allow passthrough metadata (to prevent users overriding stuff that Maven has to be responsible for for the ecosystem to work), working around the bug until the next release is a little harder than just putting on some metadata.

You'll need to alter the MSBuild script (a custom target) to rewrite the IkvmReferenceItem.AssemblyVersion metadata. 

You can do this by creating a target that runs immediately after `GetMavenIkvmReferenceItems`, and alters the contents of the IkvmReferenceItem item group.

Something like this (not tested):

```
<Target Name="FixIkvmReference" AfterTargets="GetMavenIkvmReferenceItems">
<IkvmReferenceItem Update="maven$edu.princeton.cup:java-cup:10k">
<AssemblyVersion>0.0.0.0</AssemblyVersion>
</IkvmReferenceItem>
</Target>
```

**Comment by wasabii** [comment]
> Note that SLF4J-enabling your library/application implies the addition of only a single mandatory dependency, namely slf4j-api-2.0.3.jar.

https://www.slf4j.org/manual.html

**Comment by wasabii** [comment]
So..... I think this is probably fixed. Not exactly sure, but I thought it was last year. So, closing until somebody reopens.
